spring:
  application:
    name: authapi

  server:
    port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/gangdevauth?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 159632

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 36000000